version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing Hugo..."
      - wget -q https://github.com/gohugoio/hugo/releases/download/v0.126.1/hugo_0.126.1_Linux-64bit.deb
      - sudo dpkg -i hugo_0.126.1_Linux-64bit.deb
  pre_build:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the Hugo site..."
      - hugo
artifacts:
  files:
    - '**/*'
  base-directory: public
cache:
  paths:
    - 'node_modules/**/*'